<a href="https://colab.research.google.com/github/KMVALLI/Python-for-datascienc-/blob/main/session_7_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array(([2,3,4],[5,6,7])) # arrya is a funtion in numpy in that we are giving the  trupple  #
# with in the tupple we are definding the two lists

print(a)
print(a.shape) # you will get the shape of the arrey in the form of rows and columans like matrix first row then columan

[[2 3 4]
 [5 6 7]]
(2, 3)


In [4]:
# we can use list inside the toupple and tupple in side the list we can do app list touple dictionary 
#list is a single dimentional arrey and numpy is a multtidimentionalmarray 

#efficiency of numpy comparing to normal python 

In [5]:
#for normal python memory utilization 
import sys  # it os a system related module it will gives you so many attributes at operatopnal level on like cpu memory etc 
s = range(1000)
print("Memory usage in normal way",sys.getsizeof(10)*len(s))

Memory usage in normal way 28000


In [15]:
#using numpy
import numpy as np
d = np.arange(1000)
print(d)
print(d.size) 
print(d)
print(d.itemsize) 
print("memory usage in numpy approach",d.itemsize*d.size)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [8]:
#numpuy is a opensource libiry but the code is not a open source you only use the libery 

In [11]:
#we are reshaping the matrix order 
import numpy as np
a = np.array(((1,3,5,6),(5,8,75,5)))
print(a)
print(a.shape)
a=a.reshape(4,2)  
print(a)

[[ 1  3  5  6]
 [ 5  8 75  5]]
(2, 4)
[[ 1  3]
 [ 5  6]
 [ 5  8]
 [75  5]]


In [20]:
a= a.repeat(2,1) # hear 2 is row level and 1 is columan level it will change 
print(a)
print(a.shape)

[[ 1  1  1 ...  3  3  3]
 [ 1  1  1 ...  3  3  3]
 [ 1  1  1 ...  3  3  3]
 ...
 [75 75 75 ...  5  5  5]
 [75 75 75 ...  5  5  5]
 [75 75 75 ...  5  5  5]]
(64, 32)


In [21]:
a=([0,2],[3,4],[5,6]) # with in the touple we have three lists 
print(a[1:2])

([3, 4],)


In [29]:
#fi  0    1      2    it will take n-1
a=([0,2],[3,4],[5,6]) # with in the touple we have three lists 
print(a[:3])

([3, 4], [5, 6])


In [33]:

#if you want to print at perticular value like 4
a=([0,2],[3,4],[5,6])
print(a[1]) # it will print 1 index value
b = a[1]
print(b)
b[1] # hear we are printing  4 by accesing the index value on  b list 

[3, 4]
[3, 4]


4

In [38]:
import numpy as np

b = np.array([(1,2,3),(2,5,5)])
print(b.shape)
print("maximum value ", b.max())
print("minimum value if arry ",b.min())
print("sum of the values ",b.sum())

print("for columan addition",b.sum(axis = 0)) #three colums
print("for row addition ",b.sum(axis = 1)) # two rows 




(2, 3)
maximum value  5
minimum value if arry  1
sum of the values  18
for columan addition [3 7 8]
for row addition  [ 6 12]


In [41]:
#it will give the squre root of the arreay 
print (np.sqrt(a))

[[0.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [42]:
print (np.std(a))

1.9720265943665387


In [58]:
a = ([(2,6,5,5),(2,5,6,4),(2,5,5,5)])
b = ([(2,6,9,5),(2,5,6,8),(2,5,5,5)])
print(a+b)



[(2, 6, 5, 5), (2, 5, 6, 4), (2, 5, 5, 5), (2, 6, 9, 5), (2, 5, 6, 8), (2, 5, 5, 5)]


#Stacking

In [59]:
#hstack it will print horizontally and vstack it will print vertically 
#and u can obserb shap of the matrix
print(np.shape(a))
print(np.shape(b))
print(np.hstack((a,b)))
print(np.hstack((a,b)).shape)


(3, 4)
(3, 4)
[[2 6 5 5 2 6 9 5]
 [2 5 6 4 2 5 6 8]
 [2 5 5 5 2 5 5 5]]
(3, 8)


In [60]:
print(np.shape(a))
print(np.shape(b))
print(np.vstack((a,b)))
print(np.vstack((a,b)).shape)


(3, 4)
(3, 4)
[[2 6 5 5]
 [2 5 6 4]
 [2 5 5 5]
 [2 6 9 5]
 [2 5 6 8]
 [2 5 5 5]]
(6, 4)


#sliceing

In [61]:
import numpy as np
a = np.arange(10) # it will print 0 to 9
print(a)
s = slice(2,7,2) # strting ending intervel
print(a[s]) # this will store inthe for of arretu so []

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [63]:
import numpy as np
a = np.arange(10)
print(a)
s = slice(2,7,2)

b = a[2:9:3]  # strting ending intervel
print(b.shape)
print(b)

[0 1 2 3 4 5 6 7 8 9]
(3,)
[2 5 8]
